properties:
  rulesets:
    type: array
    description: Specifies the list of Codiga Rosie ruleset names
    # At least one item must be specified
    minItems: 1
    # Only unique ruleset names are allowed
    uniqueItems: true
    items:
      type: string
      # Lowercase alphanumeric characters and dashes (-).
      # Can't start with dash.
      pattern: ^[a-z0-9][a-z0-9-]*$
      minLength: 5
      example: a-ruleset-name
required:
  - rulesets
additionalProperties: false