properties:
  rulesets:
    type: array
    description: Specifies the list of Codiga Rosie ruleset names
    # At least one item must be specified
    minItems: 1
    # Only unique ruleset names are allowed
    uniqueItems: true
    items:
      type: string
      # Lowercase alphanumeric characters and dashes (-).
      # Can't start with dash.
      # At least 5 characters long.
      pattern: ^[a-z0-9][a-z0-9-]{4,}$
      example: a-ruleset-name
required:
  - rulesets
additionalProperties: false